apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: default
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  AWS_REGION: "us-east-1"
  Messaging__RabbitMQ__Host: "rabbitmq-service"
  Messaging__RabbitMQ__Username: "guest"
  Messaging__RabbitMQ__Password: "guest"
  SWAGGER_BASE_PATH: "/users"
  NEW_RELIC_APP_NAME: "fcg-users-api"
